apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticationapi-deployment
  labels:
    app: authenticationapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticationapi
  template:
    metadata:
      labels:
        app: authenticationapi
    spec:
      containers:
        - name: authenticationapi
          image: authenticationapi
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: client
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: authenticationapi-service
spec:
  type: NodePort
  selector:
    app: authenticationapi
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31000
