apiVersion: apps/v1
kind: Deployment
metadata:
  name: referenceapi-deployment
  labels:
    app: referenceapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: referenceapi
  template:
    metadata:
      labels:
        app: referenceapi
    spec:
      containers:
        - name: referenceapi
          image: referenceapi
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: client
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: referenceapi-service
spec:
  type: NodePort
  selector:
    app: referenceapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 32000